name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit pillow reportlab
        # Install other dependencies that don't require system libraries
    
    - name: Test basic import
      run: |
        python -c "import streamlit as st; print('Streamlit imported successfully')"
        python -c "from PIL import Image; print('Pillow imported successfully')"
        python -c "from reportlab.pdfgen import canvas; print('ReportLab imported successfully')"
    
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deployment notification
      run: |
        echo "🚀 Ready for Streamlit Cloud deployment!"
        echo "Visit https://share.streamlit.io to deploy this app"
